language: python

arch:
  - arm64

python:
  - 3.7

#addons:
#  apt:
#    packages:
#      - libblas-dev
#      - liblapack-dev
#      - libatlas-base-dev
#      - gfortran

env:
  - VERSION=0.0.1

services:
  - docker

before_install:
#  - export VERSION=$(python3 - <<< "from _version import __version__;print(__version__);")
  - sudo chown -Rv $USER:$GROUP ~/.cache/pip/wheels
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - pip install --upgrade pip
  - pip install --upgrade pip setuptools wheel
  - pip install coveralls

script:
  - docker build -t nettle:$VERSION .

after_success:
  - coveralls

deploy:
  provider: script
  script: docker push nettle:$VERSION
  on:
    branch: master

notifications:
  email: false