language: python
python:
  - 3.6
  - 3.7
  - pypy3

env:
  - VERION=0.0.1

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install coveralls

script:
  - pytest --path ./tests/test.py

after_success:
  - coveralls

notifications:
  email: false