language: python

arch:
  - arm64

os: linux

python:
  - 3.6
  - 3.7
  - pypy3

env:
  - VERSION=0.0.1

services:
  - docker

install:
  - pip install --upgrade pip
  - pip install pychalk matplotlib pyfiglet sklearn numpy
  - pip install coveralls

script:
  - docker build -t nettle:$VERSION .

after_success:
  - coveralls

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

notifications:
  email: false