language: python
python:
  - 3.6
  - 3.7
  - pypy3

env:
  - DJANGO_VERSION=2.2.6

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install coveralls

script:
  - pytest

after_success:
  - coveralls

notifications:
  email: false