language: python

arch:
  - arm64

os: linux

python:
  - 3.6
  - 3.7
  - pypy3

env:
  - VERSION=0.0.1

services:
  - docker

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install coveralls

script:
  - docker build -t nettle:$VERSION .

after_success:
  - coveralls

notifications:
  email: false